USE [master]
GO

/****** Object:  Database [flaschcard]    Script Date: 4/30/2019 5:30:23 PM ******/
CREATE DATABASE [flaschcard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'flaschcard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\flaschcard.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'flaschcard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\flaschcard_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [flaschcard] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [flaschcard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [flaschcard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [flaschcard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [flaschcard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [flaschcard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [flaschcard] SET ARITHABORT OFF 
GO

ALTER DATABASE [flaschcard] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [flaschcard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [flaschcard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [flaschcard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [flaschcard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [flaschcard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [flaschcard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [flaschcard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [flaschcard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [flaschcard] SET  ENABLE_BROKER 
GO

ALTER DATABASE [flaschcard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [flaschcard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [flaschcard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [flaschcard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [flaschcard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [flaschcard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [flaschcard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [flaschcard] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [flaschcard] SET  MULTI_USER 
GO

ALTER DATABASE [flaschcard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [flaschcard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [flaschcard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [flaschcard] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [flaschcard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [flaschcard] SET  READ_WRITE 
GO

